# Generated by Django 4.0.3 on 2022-05-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_rentcar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandLogos',
        ),
    ]
