# Generated by Django 4.0.3 on 2022-05-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0007_rentcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BrandLogos',
        ),
        migrations.AlterField(
            model_name='newcar',
            name='transmission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.transmission'),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='transmission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.transmission'),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='transmission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.transmission'),
        ),
    ]
