# Generated by Django 4.0.3 on 2022-05-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0008_transmission_delete_brandlogos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='transmission_type',
            field=models.CharField(max_length=20),
        ),
    ]
