# Generated by Django 4.0.3 on 2022-05-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0011_alter_newcar_transmission_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmission',
            old_name='transmission_type',
            new_name='transmission_t',
        ),
    ]
