# Generated by Django 4.0.3 on 2022-05-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_rename_transmission_type_transmission_transmission_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rentcar',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usedcar',
            name='transmission_type',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20, null=True),
        ),
    ]
