# Generated by Django 4.0.3 on 2022-05-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0012_alter_newcar_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Cars.brandl'),
        ),
    ]
