# Generated by Django 4.0.3 on 2022-05-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0013_alter_newcar_transmission_type_and_more'),
        ('Cars', '0015_alter_newcar_brand_alter_rentcar_brand_and_more'),
    ]

    operations = [
    ]
